/**
 * Test-only fault injection for HTTP integration tests.
 *
 * The capability secret is generated by the API test runner for each run. It
 * is never configured in deployed environments, and production explicitly
 * rejects all simulation headers even if the feature flag is misconfigured.
 */
export type AuthTestSimulation =
  | "redis-down"
  | "supabase-down"
  | "notification-down"

const SIMULATION_HEADER = "x-test-simulate-error"
const SIMULATION_SECRET_HEADER = "x-auth-test-simulation-secret"
const TEST_SIMULATIONS = new Set<AuthTestSimulation>([
  "redis-down",
  "supabase-down",
  "notification-down",
])

export function getAuthTestSimulation(req: Request): AuthTestSimulation | null {
  const expectedSecret = process.env.AUTH_TEST_SIMULATION_SECRET
  const suppliedSecret = req.headers.get(SIMULATION_SECRET_HEADER)

  if (
    process.env.NODE_ENV === "production" ||
    process.env.AUTH_TEST_SIMULATION !== "1" ||
    !expectedSecret ||
    expectedSecret.length < 32 ||
    suppliedSecret !== expectedSecret
  ) {
    return null
  }

  const requestedSimulation = req.headers.get(SIMULATION_HEADER)
  return requestedSimulation && TEST_SIMULATIONS.has(requestedSimulation as AuthTestSimulation)
    ? requestedSimulation as AuthTestSimulation
    : null
}
